### DISCUSSION TITLE
Docker版本无法定时更新

### DISCUSSION THREAD

**Discussion by pooneyy** [Guovin/iptv-api#936] [Q&A] [answered]
我使用docker-compose部署，只在容器启动的时候更新了数据，环境变量里配置的`UPDATE_CRON`到点时没有自动更新，不知道是什么原因？
以下是我的docker-compose.yml
```yaml
services:
    name:
        image: guovern/iptv-api:latest
        container_name: iptv-api
        deploy:
            resources:
                limits:
                    cpus: "0"
                    memory: "0"
        restart: always
        privileged: true
        volumes:
          - ./config:/iptv-api/config
          - ./output:/iptv-api/output
        ports:
            - 127.0.0.1:22003:8000
        environment:
          - TZ=Asia/Shanghai
          - APP_PORT=8000
          - UPDATE_CRON="0 22,10 * * *"
        tty: true
        stdin_open: true
```
这个是我的日志，我也不知道为什么只有开头几行有日期时间
[iptv-api-20250225192154.log](https://github.com/user-attachments/files/18963257/iptv-api-20250225192154.log)
