### ISSUE TITLE
[Bug]: : TypeError: tuple indices must be integers or slices, not str(no crontab for root)

### ISSUE THREAD

**Issue by denny0810** [Guovin/iptv-api#963]
### Don't skip these steps | 不要跳过这些步骤

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**限制**
- [x] I am sure that this is a running error exception problem and will not submit any problems unrelated to this project | 我确定这是运行报错异常问题，不会提交任何与本项目无关的问题
- [x] I have searched and double-checked that there are no similar issues that have been created | 我已经通过搜索并仔细检查过没有存在已经创建的类似问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [x] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

docker version: 1.6.2
docker compose:
```
version: '3'

services:
  iptv-api:
    image: guovern/iptv-api:lite
    container_name: iptv-api
    environment:
      - TZ=Asia/Shanghai
      - APP_PORT=3101 # 8000
      - UPDATE_CRON=0 6,18 * * *
    volumes:
      - /opt/docker/iptvapi/config:/iptv-api-lite/config
      - /opt/docker/iptvapi/output:/iptv-api-lite/output
    restart: unless-stopped
# limit the log size
    logging:
#       driver: none
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
    network_mode: host
```
已经按照 #962 删除/output所有文件。

### Error log | 报错日志

stderr: no crontab for root
stderr: [2025-03-08 10:04:40 +0800] [21] [INFO] Starting gunicorn 23.0.0
stderr: [2025-03-08 10:04:40 +0800] [21] [INFO] Listening at: http://0.0.0.0:3101 (21)
stderr: [2025-03-08 10:04:40 +0800] [21] [INFO] Using worker: sync
stderr: [2025-03-08 10:04:40 +0800] [23] [INFO] Booting worker with pid: 23
stdout: ℹ️ IPTV-API Version: 1.6.2
stderr: Traceback (most recent call last):
stderr:   File "/iptv-api-lite/main.py", line 227, in <module>
stderr:     loop.run_until_complete(update_source.start())
stderr:     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
stderr:     return future.result()
stderr:            ~~~~~~~~~~~~~^^
stderr:   File "/iptv-api-lite/main.py", line 211, in start
stderr:     await self.main()
stderr:   File "/iptv-api-lite/main.py", line 120, in main
stderr:     self.channel_items = get_channel_items()
stderr:                          ~~~~~~~~~~~~~~~~~^^
stderr:   File "/iptv-api-lite/utils/channel.py", line 138, in get_channel_items
stderr:     pure_url = info["url"].partition("$")[0]
stderr:                ~~~~^^^^^^^
stderr: TypeError: tuple indices must be integers or slices, not str
